

availableData <- function() {

    as.data.frame(matrix(c("B1",  "",  "Exchange rates and Trade Weighted Index",
                           "B2",  "",  "Wholesale interest rates",
                           "B3",  "",  "Retail interest rates on lending and deposits",
                           "B4",  "",  "Foreign exchange turnover ($m daily averages)",
                           "B6",  "",  "Yields on loans",
                           "B7",  "",  "Costs of Deposits",
                           "B10", "",  "TWI weights",
                           "B13", "",  "Historical TWI weights",
                           "B20", "",  "New residential mortgage standard interest rates",
                           "B21", "",  "New residential mortgage special interest rates",
                           "B25", "",  "New interest bearing call savings account interest rates",
                           "B26", "",  "New interest bearing term deposit interest rates",
                           "B27", "",  "New interest bearing term PIE deposits interest rates",
                           "B30", "",  "New residential mortgage weighted average interest rates",

                           "C5",  "",  "Sector lending (registered banks and non-bank lending institutions)",
                           "C12", "",  "Credit card balances",
                           "C13", "",  "Credit card spending",
                           "C21", "",  "Key household financial statistics ($m)",
                           "C22", "",  "Household balance sheet ($m)",
                           "C30", "",  "New residential mortgage lending by loan-to-valuation ratio (LVR) compliance data",
                           "C31", "",  "New residential mortgage lending by borrower type",
                           "C32", "",  "New and Existing Residential Mortgage Lending by Payment type",
                           "C33", "",  "New Residential Mortgage Lending by Purpose",
                           "C35", "",  "Residential mortgage loan reconciliation",
                           "C40", "",  "Residential mortgage lending by debt-to-income (DTI) purpose use",
                           "C41", "",  "Residential mortgage borrower gross income (BGI)",
                           "C50", "",  "Money and credit aggregates (depository corporations)",
                           "C51", "",  "Other depository corporations analytical accounts",
                           "C52", "",  "Depository corporations analytical accounts",
                           "C55", "",  "Other financial corporations analytical accounts",
                           "C60", "",  "Credit conditions survey",
                           "C65", "",  "Bank Customer Lending flows",
                           "C66", "",  "Bank Customer Lending stocks",
                           "C70", "",  "New Lending by Purpose",
                           "C71", "",  "New lending fully secured by residential mortgage",

                           "D3",  "X", "Open market operations",
                           "D9",  "",  "Government bond turnover",
                           "D10", "X", "Influences on settlement cash",
                           "D12", "X", "Standing facilities",
                           "D30", "",  "Holdings of central government debt securities (nominal value)",
                           "D31", "",  "Non-resident holdings of individual bonds (nominal value)",
                           "D35", "",  "Holdings of Kauri bonds (nominal value)",

                           "E1",  "X", "New Zealand's official overseas reserves",
                           "E2",  "",  "New Zealand's position with the IMF",

                           "F3",  "X", "Bank notes in the hands of the public",
                           "F4",  "X", "Coin mintings",
                           "F5",  "X", "Reserve Bank foreign currency assets and liabilities",

                           "H1",  "",  "Household Inflation Expectations",
                           "H2",  "",  "Housing and Employment",
                           "H3",  "",  "Cash Use",

                           "J10", "",  "Insurance: Income Statement",
                           "J20", "",  "Insurance: Balance Sheet",

                           "L1",  "",  "Mismatch ratios",
                           "L2",  "",  "Core funding ratio",
                           "L3",  "",  "Face value of funding by residual maturity ($m)",

                           "M1",  "",  "Prices",
                           "M2",  "",  "Consumption",
                           "M3",  "",  "Investment",
                           "M4",  "",  "Domestic trade",
                           "M5",  "",  "Gross Domestic Product",
                           "M6",  "",  "National saving (year ended March)",
                           "M7",  "",  "Balance of Payments and International Investment Position",
                           "M8",  "",  "Overseas trade",
                           "M9",  "",  "Labour market",
                           "M10", "",  "Housing",
                           "M12", "",  "Population and migration",
                           "M14", "",  "Survey of expectations",
                           "M15", "",  "Business Expectations Survey",

                           "R1",  "",  "Reserve Bank balance sheet ($m)",
                           "R2",  "",  "Reserve Bank statistical balance sheet ($m)",
                           "R3",  "",  "Reserve Bank analytical accounts ($m)",

                           "S10", "",  "Banks: Balance sheet ($m)",
                           "S20", "",  "Banks: Summary income statement and related ratios",
                           "S21", "",  "Banks: Income statement ($m)",
                           "S30", "",  "Banks: Assets - Loans by sector",
                           "S31", "",  "Banks: Assets - Loans by purpose ($m)",
                           "S32", "",  "Banks: Assets - Loans by product ($m)",
                           "S33", "",  "Banks: Assets - Loans fully secured by residential mortgage by repricing ($m)",
                           "S34", "",  "Banks: Assets - Loans and Repos by Industry ($m)",
                           "S35", "",  "Banks: Assets - Loans by Business Size",
                           "S36", "",  "Banks: Assets - Loans by Product",
                           "S37", "",  "Banks: Assets - Agriculture Loans by Product",
                           "S40", "",  "Banks: Liabilities - Deposits by sector ($m)",
                           "S41", "",  "Banks: Liabilities - Deposits by industry ($m)",
                           "S42", "",  "Banks: Liabilities - Deposits by repricing",
                           "S45", "", "Banks: Liabilities - Deposits by size (value)",
                           "S46", "", "Banks: Liabilities - Deposits by size (number)",
                           "S50", "",  "Banks: Assets - Loans by Asset Quality",
                           "S51", "",  "Banks: Assets - Business Loans by Asset Quality",

                           "SDDS", "X", "NZ's international reserves and foreign currency liquidity",

                           "T1",  "",  "Non banks: Balance sheet ($m)",
                           "T4",  "",  "Non banks: Funding and claims by sector ($m)",
                           "T11", "",  "Savings institutions: Balance sheet ($m)",
                           "T21", "",  "Deposit taking finance companies: Balance sheet ($m)",
                           "T31", "",  "Non-deposit taking finance companies: Balance sheet ($m)",
                           "T40", "",  "Funds under management ($m)",
                           "T41", "",  "Managed fund assets ($m)",
                           "T42", "",  "Life insurance ($m)",
                           "T43", "",  "KiwiSaver ($m)",
                           "T44", "",  "Other registered superannuation ($m)",
                           "T45", "",  "Retail unit trusts ($m)",
                           "T46", "",  "Cash management trusts ($m)",
                           "T47", "",  "Wholesale trusts ($m)",
                           "T48", "",  "Wholesale trusts and other funds ($m)"
                           ),
                         ncol = 3, byrow = TRUE,
                         dimnames = list(NULL, c("Series", "Standard_Format", "Description"))),
                  stringsAsFactors = FALSE)

}
